Reports status of the integration commit after the build has finished
HackAttack/bamboo-github-status pull request #17
Opened 2016-10-27 17:51 UTC by alindeman

When using the [branch updater](https://confluence.atlassian.com/bamboo/using-plan-branches-289276872.html#Usingplanbranches-Branchupdater) feature of Bamboo, while the tests are run against an integrated branch, the commit is not pushed until the build is completed. This PR proposes pushing status to the merge commit resulting from a branch updater after the entire chain is finished.

2017-03-08 15:46 UTC, alindeman commented
@HackAttack Any thoughts on this? We've been using this code on our Bamboo instance for some time now. I'm happy to answer any questions or concerns.

2017-03-08 19:01 UTC, HackAttack commented
Thanks for the ping @alindeman. I suspect this, #14, and #20 all touch the same code—will take a closer look this week.

2017-03-22 06:08 UTC, HackAttack requested changes
Sorry this took so long for me to get to. I like this feature, but I have a couple design changes and questions when you get a chance.

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +        if (stageExecution.isCompleted() || stageExecution.getChainExecution().isCompleted()) {
I don’t like moving this logic into the superclass, because it means now we have to perform the check for whether we’re starting or stopping manually, rather than using the hooks that the system provides us.

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +    void updateStatusForMerge(ChainResultsSummary resultsSummary, ChainExecution chainExecution) {
This logic is only pertinent to the PostChainAction, so it should live there rather than in the superclass.

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +        RepositoryDefinition defaultRepo = PlanHelper.getDefaultRepositoryDefinition(chain);
Can we reuse the existing code (Configuration.ghReposFrom) for extracting the repo?

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +        } else if (mergeResultSummary.getMergeState() != MergeResultState.SUCCESS) {
I think the check should be against getPushState() instead so that we don’t attempt to set status on a commit that wasn’t successfully pushed.

Additionally, if we also check the merge state and set the commit status to failure in that case, would that fix #14?

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +        if (chain == null) {
I don’t think this can happen, since we are passing in a known good PlanKey.

2017-03-22 06:08 UTC, HackAttack commented on src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java
> +            updateStatus(stageExecution);
At the point this method is called, haven’t all the stages been updated? It seems like this will do it a second time.

2022-08-12 21:16 UTC, closed without merging